// @generated by protoc-gen-connect-es v0.12.0
// @generated from file api/v1alpha1/pbx/service.proto (package api.v1alpha1.pbx, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ActivatePbxUserRequest, ActivatePbxUserResponse, AddUsersToRingGroupRequest, AddUsersToRingGroupResponse, AssignRandomGroupExtensionRequest, AssignRandomGroupExtensionResponse, AssignRandomUserExtensionRequest, AssignRandomUserExtensionResponse, CreateRingGroupRequest, CreateRingGroupResponse, DeactivatePbxUserRequest, DeactivatePbxUserResponse, DeleteRingGroupRequest, DeleteRingGroupResponse, ListPbxUsersRequest, ListPbxUsersResponse, ListRingGroupsRequest, ListRingGroupsResponse, RemoveUsersFromRingGroupRequest, RemoveUsersFromRingGroupResponse, UpdateRingGroupRequest, UpdateRingGroupResponse, UpdateUserExtensionRequest, UpdateUserExtensionResponse } from "./service_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * PBX is responsible for PBX user management and SIP configuration.
 *
 * @generated from service api.v1alpha1.pbx.PBX
 */
export const PBX = {
  typeName: "api.v1alpha1.pbx.PBX",
  methods: {
    /**
     * Lists all PBX Users for the authenticated callers ORG
     * Required permissions:
     *   PBX-MANAGER
     * Errors:
     *   - grpc.PermissionDenied: Caller doesn't have the required permissions.
     *   - grpc.Internal: An internal error occurred.
     *   - grpc.Unavailable: The operation is currently unavailable. Likely a transient issue with a downstream service.
     *
     * @generated from rpc api.v1alpha1.pbx.PBX.ListPbxUsers
     */
    listPbxUsers: {
      name: "ListPbxUsers",
      I: ListPbxUsersRequest,
      O: ListPbxUsersResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Activates a given PBX User for the authenticated callers ORG
     * Required permissions:
     *   PBX-MANAGER
     * Errors:
     *   - grpc.InvalidArgument: The userID is an invalid format.
     *   - grpc.NotFound: The user DNE or is not in the callers ORG.
     *   - grpc.PermissionDenied: Caller doesn't have the required permissions.
     *   - grpc.Internal: An internal error occurred.
     *   - grpc.Unavailable: The operation is currently unavailable. Likely a transient issue with a downstream service.
     *
     * @generated from rpc api.v1alpha1.pbx.PBX.ActivatePbxUser
     */
    activatePbxUser: {
      name: "ActivatePbxUser",
      I: ActivatePbxUserRequest,
      O: ActivatePbxUserResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Deactivates a given PBX User for the authenticated callers ORG
     * Required permissions:
     *   PBX-MANAGER
     * Errors:
     *   - grpc.InvalidArgument: The userID is an invalid format.
     *   - grpc.NotFound: The user DNE or is not in the callers ORG.
     *   - grpc.PermissionDenied: Caller doesn't have the required permissions.
     *   - grpc.Internal: An internal error occurred.
     *   - grpc.Unavailable: The operation is currently unavailable. Likely a transient issue with a downstream service.
     *
     * @generated from rpc api.v1alpha1.pbx.PBX.DeactivatePbxUser
     */
    deactivatePbxUser: {
      name: "DeactivatePbxUser",
      I: DeactivatePbxUserRequest,
      O: DeactivatePbxUserResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Updates a PBX Users extension for the authenticated callers ORG
     * Required permissions:
     *   PBX-MANAGER
     * Errors:
     *   - grpc.InvalidArgument: The userID is an invalid format. Or the extension has an invalid length.
     *   - grpc.NotFound: The user DNE or is not in the callers ORG.
     *   - grpc.FailedPrecondition: The extension is already in use.
     *   - grpc.PermissionDenied: Caller doesn't have the required permissions.
     *   - grpc.Internal: An internal error occurred.
     *   - grpc.Unavailable: The operation is currently unavailable. Likely a transient issue with a downstream service.
     *
     * @generated from rpc api.v1alpha1.pbx.PBX.UpdateUserExtension
     */
    updateUserExtension: {
      name: "UpdateUserExtension",
      I: UpdateUserExtensionRequest,
      O: UpdateUserExtensionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Creates a ring group for the authenticated callers ORG
     * Required permissions:
     *   PBX-MANAGER
     * Errors:
     *   - grpc.InvalidArgument: The name is blank, has invalid characters, or the extension has an invalid length.
     *   - grpc.FailedPrecondition: The extension or name is already in use.
     *   - grpc.PermissionDenied: Caller doesn't have the required permissions.
     *   - grpc.Internal: An internal error occurred.
     *   - grpc.Unavailable: The operation is currently unavailable. Likely a transient issue with a downstream service.
     *
     * @generated from rpc api.v1alpha1.pbx.PBX.CreateRingGroup
     */
    createRingGroup: {
      name: "CreateRingGroup",
      I: CreateRingGroupRequest,
      O: CreateRingGroupResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Lists all ring groups for the authenticated callers ORG
     * Required permissions:
     *   PBX-MANAGER
     * Errors:
     *   - grpc.PermissionDenied: Caller doesn't have the required permissions.
     *   - grpc.Internal: An internal error occurred.
     *   - grpc.Unavailable: The operation is currently unavailable. Likely a transient issue with a downstream service.
     *
     * @generated from rpc api.v1alpha1.pbx.PBX.ListRingGroups
     */
    listRingGroups: {
      name: "ListRingGroups",
      I: ListRingGroupsRequest,
      O: ListRingGroupsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Updates a ring group for the authenticated callers ORG
     * Required permissions:
     *   PBX-MANAGER
     * Errors:
     *   - grpc.InvalidArgument: The name is blank, has invalid characters, or the extension has an invalid length.
     *   - grpc.FailedPrecondition: The extension or name is already in use.
     *   - grpc.NotFound: The group DNE or is not in the callers ORG || One or more of the users DNE or is not in the callers ORG.
     *   - grpc.PermissionDenied: Caller doesn't have the required permissions.
     *   - grpc.Internal: An internal error occurred.
     *   - grpc.Unavailable: The operation is currently unavailable. Likely a transient issue with a downstream service.
     *
     * @generated from rpc api.v1alpha1.pbx.PBX.UpdateRingGroup
     */
    updateRingGroup: {
      name: "UpdateRingGroup",
      I: UpdateRingGroupRequest,
      O: UpdateRingGroupResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Adds users to a ring group for the authenticated callers ORG
     * Required permissions:
     *   PBX-MANAGER
     * Errors:
     *   - grpc.InvalidArgument: The group or one or more of the userIDs have an invalid format.
     *   - grpc.NotFound: The group or a user DNE or is not in the callers ORG.
     *   - grpc.PermissionDenied: Caller doesn't have the required permissions.
     *   - grpc.Internal: An internal error occurred.
     *   - grpc.Unavailable: The operation is currently unavailable. Likely a transient issue with a downstream service.
     *
     * @generated from rpc api.v1alpha1.pbx.PBX.AddUsersToRingGroup
     */
    addUsersToRingGroup: {
      name: "AddUsersToRingGroup",
      I: AddUsersToRingGroupRequest,
      O: AddUsersToRingGroupResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Removes users to a ring group for the authenticated callers ORG
     * Required permissions:
     *   PBX-MANAGER
     * Errors:
     *   - grpc.NotFound: The group DNE or is not in the callers ORG.
     *   - grpc.PermissionDenied: Caller doesn't have the required permissions.
     *   - grpc.Internal: An internal error occurred.
     *   - grpc.Unavailable: The operation is currently unavailable. Likely a transient issue with a downstream service.
     *
     * @generated from rpc api.v1alpha1.pbx.PBX.RemoveUsersFromRingGroup
     */
    removeUsersFromRingGroup: {
      name: "RemoveUsersFromRingGroup",
      I: RemoveUsersFromRingGroupRequest,
      O: RemoveUsersFromRingGroupResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Deletes a ring group for the authenticated callers ORG
     * Required permissions:
     *   PBX-MANAGER
     * Errors:
     *   - grpc.InvalidArgument: The groupID is an invalid format.
     *   - grpc.NotFound: The group DNE or is not in the callers ORG.
     *   - grpc.PermissionDenied: Caller doesn't have the required permissions.
     *   - grpc.Internal: An internal error occurred.
     *   - grpc.Unavailable: The operation is currently unavailable. Likely a transient issue with a downstream service.
     *
     * @generated from rpc api.v1alpha1.pbx.PBX.DeleteRingGroup
     */
    deleteRingGroup: {
      name: "DeleteRingGroup",
      I: DeleteRingGroupRequest,
      O: DeleteRingGroupResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Randomly assigns a PBX User an extension for the authenticated callers ORG
     * Required permissions:
     *   PBX-MANAGER
     * Errors:
     *   - grpc.InvalidArgument: The userID is an invalid format.
     *   - grpc.NotFound: The user DNE or is not in the callers ORG.
     *   - grpc.PermissionDenied: Caller doesn't have the required permissions.
     *   - grpc.Internal: An internal error occurred.
     *   - grpc.Unavailable: The operation is currently unavailable. Likely a transient issue with a downstream service.
     *
     * @generated from rpc api.v1alpha1.pbx.PBX.AssignRandomUserExtension
     */
    assignRandomUserExtension: {
      name: "AssignRandomUserExtension",
      I: AssignRandomUserExtensionRequest,
      O: AssignRandomUserExtensionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Randomly assigns a PBX group an extension for the authenticated callers ORG
     * Required permissions:
     *   PBX-MANAGER
     * Errors:
     *   - grpc.InvalidArgument: The groupID is an invalid format.
     *   - grpc.NotFound: The group DNE or is not in the callers ORG.
     *   - grpc.PermissionDenied: Caller doesn't have the required permissions.
     *   - grpc.Internal: An internal error occurred.
     *   - grpc.Unavailable: The operation is currently unavailable. Likely a transient issue with a downstream service.
     *
     * @generated from rpc api.v1alpha1.pbx.PBX.AssignRandomGroupExtension
     */
    assignRandomGroupExtension: {
      name: "AssignRandomGroupExtension",
      I: AssignRandomGroupExtensionRequest,
      O: AssignRandomGroupExtensionResponse,
      kind: MethodKind.Unary,
    },
  }
};

