// @generated by protoc-gen-es v1.6.0 with parameter "target=js+dts"
// @generated from file wfo/vanalytics/v2/filter.proto (package wfo.vanalytics.v2, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage, Timestamp } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import type { TranscriptQuery } from "./transcript_pb.js";

/**
 * @generated from message wfo.vanalytics.v2.CreateFilterRequest
 */
export declare class CreateFilterRequest extends Message<CreateFilterRequest> {
  /**
   * The filter resource to create.
   *
   * @generated from field: wfo.vanalytics.v2.Filter filter = 1;
   */
  filter?: Filter;

  constructor(data?: PartialMessage<CreateFilterRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "wfo.vanalytics.v2.CreateFilterRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateFilterRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateFilterRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateFilterRequest;

  static equals(a: CreateFilterRequest | PlainMessage<CreateFilterRequest> | undefined, b: CreateFilterRequest | PlainMessage<CreateFilterRequest> | undefined): boolean;
}

/**
 * @generated from message wfo.vanalytics.v2.CreateFilterResponse
 */
export declare class CreateFilterResponse extends Message<CreateFilterResponse> {
  /**
   * The filter resource that was created.
   *
   * @generated from field: wfo.vanalytics.v2.Filter filter = 1;
   */
  filter?: Filter;

  constructor(data?: PartialMessage<CreateFilterResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "wfo.vanalytics.v2.CreateFilterResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateFilterResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateFilterResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateFilterResponse;

  static equals(a: CreateFilterResponse | PlainMessage<CreateFilterResponse> | undefined, b: CreateFilterResponse | PlainMessage<CreateFilterResponse> | undefined): boolean;
}

/**
 * A filter resource in the Vanalytics API.
 *
 * @generated from message wfo.vanalytics.v2.Filter
 */
export declare class Filter extends Message<Filter> {
  /**
   * Output only. The unique id of this filter.
   *
   * @generated from field: int64 filter_sid = 1;
   */
  filterSid: bigint;

  /**
   * Required. The name of this filter. Must be non empty and unique across all
   * filters within an organization.
   *
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * The search request to be used to filter transcripts.
   *
   * @generated from field: wfo.vanalytics.v2.TranscriptQuery transcript_query = 4;
   */
  transcriptQuery?: TranscriptQuery;

  /**
   * Output only. The timestamp when this filter was created. Assigned by the
   * server.
   *
   * @generated from field: google.protobuf.Timestamp create_time = 5;
   */
  createTime?: Timestamp;

  /**
   * Output only. The version of this filter.
   *
   * @generated from field: int64 version = 6;
   */
  version: bigint;

  constructor(data?: PartialMessage<Filter>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "wfo.vanalytics.v2.Filter";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Filter;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Filter;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Filter;

  static equals(a: Filter | PlainMessage<Filter> | undefined, b: Filter | PlainMessage<Filter> | undefined): boolean;
}

