// @generated by protoc-gen-connect-es v0.13.0
// @generated from file wfo/vanalytics/v2/service.proto (package wfo.vanalytics.v2, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { SearchTranscriptsRequest, SearchTranscriptsResponse } from "./transcript_pb.js";
import { MethodKind } from "@bufbuild/protobuf";
import { CreateFilterRequest, DeleteFilterRequest, DeleteFilterResponse, Filter, GetFilterRequest, ListFiltersRequest, ListFiltersResponse, UpdateFilterRequest } from "./filter_pb.js";

/**
 * @generated from service wfo.vanalytics.v2.Vanalytics
 */
export const Vanalytics = {
  typeName: "wfo.vanalytics.v2.Vanalytics",
  methods: {
    /**
     * SearchTranscripts searches transcripts by search criteria. The search response
     * contains one page of transcript hits. Traversing the paginated hits is
     * achieved by making use of the given page token.
     *
     * @generated from rpc wfo.vanalytics.v2.Vanalytics.SearchTranscripts
     */
    searchTranscripts: {
      name: "SearchTranscripts",
      I: SearchTranscriptsRequest,
      O: SearchTranscriptsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * CreateFilter creates a new filter. The filter contains a transcript query
     * to filter transcripts.
     *
     * @generated from rpc wfo.vanalytics.v2.Vanalytics.CreateFilter
     */
    createFilter: {
      name: "CreateFilter",
      I: CreateFilterRequest,
      O: Filter,
      kind: MethodKind.Unary,
    },
    /**
     * ListFilters lists filters.
     *
     * @generated from rpc wfo.vanalytics.v2.Vanalytics.ListFilters
     */
    listFilters: {
      name: "ListFilters",
      I: ListFiltersRequest,
      O: ListFiltersResponse,
      kind: MethodKind.Unary,
    },
    /**
     * UpdateFilter updates a filter transcript query and/or name.
     *
     * @generated from rpc wfo.vanalytics.v2.Vanalytics.UpdateFilter
     */
    updateFilter: {
      name: "UpdateFilter",
      I: UpdateFilterRequest,
      O: Filter,
      kind: MethodKind.Unary,
    },
    /**
     * DeleteFilter deletes filter given a filter_sid.
     *
     * @generated from rpc wfo.vanalytics.v2.Vanalytics.DeleteFilter
     */
    deleteFilter: {
      name: "DeleteFilter",
      I: DeleteFilterRequest,
      O: DeleteFilterResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetFilter gets filter given a filter_sid or name.
     *
     * @generated from rpc wfo.vanalytics.v2.Vanalytics.GetFilter
     */
    getFilter: {
      name: "GetFilter",
      I: GetFilterRequest,
      O: Filter,
      kind: MethodKind.Unary,
    },
  }
};

