// @generated by protoc-gen-es v1.7.1 with parameter "target=js+dts"
// @generated from file api/v1alpha1/sentinel/entities.proto (package api.v1alpha1.sentinel, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3, Timestamp } from "@bufbuild/protobuf";
import { Level } from "../../commons/logging_pb.js";

/**
 * @generated from message api.v1alpha1.sentinel.SentinelEvent
 */
export const SentinelEvent = proto3.makeMessageType(
  "api.v1alpha1.sentinel.SentinelEvent",
  () => [
    { no: 1, name: "log_event", kind: "message", T: LogEvent, oneof: "event" },
  ],
);

/**
 * @generated from message api.v1alpha1.sentinel.LogEvent
 */
export const LogEvent = proto3.makeMessageType(
  "api.v1alpha1.sentinel.LogEvent",
  () => [
    { no: 3, name: "trace_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "session_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "location", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "stack_trace", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "timestamp", kind: "message", T: Timestamp },
    { no: 9, name: "metadata", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "scalar", T: 9 /* ScalarType.STRING */} },
    { no: 10, name: "severity", kind: "enum", T: proto3.getEnumType(Level) },
  ],
);

/**
 * @generated from message api.v1alpha1.sentinel.SendEventsReq
 */
export const SendEventsReq = proto3.makeMessageType(
  "api.v1alpha1.sentinel.SendEventsReq",
  () => [
    { no: 1, name: "events", kind: "message", T: SentinelEvent, repeated: true },
  ],
);

/**
 * @generated from message api.v1alpha1.sentinel.SendEventsRes
 */
export const SendEventsRes = proto3.makeMessageType(
  "api.v1alpha1.sentinel.SendEventsRes",
  [],
);

