// @generated by protoc-gen-es v1.7.2 with parameter "target=js+dts"
// @generated from file api/v1alpha1/wfm/wfm_adherence_app.proto (package api.v1alpha1.wfm, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * Request message for the HelloWorldWFMAdherence RPC.
 *
 * @generated from message api.v1alpha1.wfm.HelloWorldWFMAdherenceRequest
 */
export declare class HelloWorldWFMAdherenceRequest extends Message<HelloWorldWFMAdherenceRequest> {
  constructor(data?: PartialMessage<HelloWorldWFMAdherenceRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "api.v1alpha1.wfm.HelloWorldWFMAdherenceRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): HelloWorldWFMAdherenceRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): HelloWorldWFMAdherenceRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): HelloWorldWFMAdherenceRequest;

  static equals(a: HelloWorldWFMAdherenceRequest | PlainMessage<HelloWorldWFMAdherenceRequest> | undefined, b: HelloWorldWFMAdherenceRequest | PlainMessage<HelloWorldWFMAdherenceRequest> | undefined): boolean;
}

/**
 * Response message for the HelloWorldWFMAdherence RPC.
 *
 * @generated from message api.v1alpha1.wfm.HelloWorldWFMAdherenceResponse
 */
export declare class HelloWorldWFMAdherenceResponse extends Message<HelloWorldWFMAdherenceResponse> {
  /**
   * A string containing the hello world message
   *
   * @generated from field: string hello_message = 1;
   */
  helloMessage: string;

  constructor(data?: PartialMessage<HelloWorldWFMAdherenceResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "api.v1alpha1.wfm.HelloWorldWFMAdherenceResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): HelloWorldWFMAdherenceResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): HelloWorldWFMAdherenceResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): HelloWorldWFMAdherenceResponse;

  static equals(a: HelloWorldWFMAdherenceResponse | PlainMessage<HelloWorldWFMAdherenceResponse> | undefined, b: HelloWorldWFMAdherenceResponse | PlainMessage<HelloWorldWFMAdherenceResponse> | undefined): boolean;
}

