// @generated by protoc-gen-connect-es v0.8.6
// @generated from file api/v0alpha/fts.proto (package api.v0alpha, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetUploadFileUrlReq, GetUploadFileUrlRes } from "./fts_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service api.v0alpha.FTS
 */
export const FTS = {
  typeName: "api.v0alpha.FTS",
  methods: {
    /**
     * @generated from rpc api.v0alpha.FTS.GetUploadFileUrl
     */
    getUploadFileUrl: {
      name: "GetUploadFileUrl",
      I: GetUploadFileUrlReq,
      O: GetUploadFileUrlRes,
      kind: MethodKind.Unary,
    },
  }
};

