// @generated by protoc-gen-connect-es v0.13.0
// @generated from file api/v1alpha1/vanalytics/support_service.proto (package api.v1alpha1.vanalytics, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { DeleteFlagTranscriptRequest, DeleteFlagTranscriptResponse } from "./flag_transcript_pb.js";
import { MethodKind } from "@bufbuild/protobuf";
import { ListFlaggedTranscriptsByOrgIdRequest, SearchResponse } from "./transcript_pb.js";

/**
 * @generated from service api.v1alpha1.vanalytics.VanalyticsSupport
 */
export const VanalyticsSupport = {
  typeName: "api.v1alpha1.vanalytics.VanalyticsSupport",
  methods: {
    /**
     * DeleteFlagTranscript deletes a flag transcript.
     *
     * @generated from rpc api.v1alpha1.vanalytics.VanalyticsSupport.DeleteFlagTranscript
     */
    deleteFlagTranscript: {
      name: "DeleteFlagTranscript",
      I: DeleteFlagTranscriptRequest,
      O: DeleteFlagTranscriptResponse,
      kind: MethodKind.Unary,
    },
    /**
     * ListFlaggedTranscriptsByOrgId lists flagged transcripts.
     *
     * @generated from rpc api.v1alpha1.vanalytics.VanalyticsSupport.ListFlaggedTranscriptsByOrgId
     */
    listFlaggedTranscriptsByOrgId: {
      name: "ListFlaggedTranscriptsByOrgId",
      I: ListFlaggedTranscriptsByOrgIdRequest,
      O: SearchResponse,
      kind: MethodKind.Unary,
    },
  }
};

