// @generated by protoc-gen-es v1.9.0 with parameter "target=js+dts"
// @generated from file api/commons/classifier.proto (package api.commons, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * these are the types that will be used for File Templates
 *
 * @generated from enum api.commons.ClassifierEntityType
 */
export const ClassifierEntityType = /*@__PURE__*/ proto3.makeEnum(
  "api.commons.ClassifierEntityType",
  [
    {no: 0, name: "CET_UNKNOWN"},
    {no: 1, name: "CET_CREDIT_CARD"},
    {no: 2, name: "CET_CRYPTO"},
    {no: 3, name: "CET_DATE_TIME"},
    {no: 4, name: "CET_EMAIL_ADDRESS"},
    {no: 5, name: "CET_IBAN_CODE"},
    {no: 6, name: "CET_IP_ADDRESS"},
    {no: 7, name: "CET_NRP"},
    {no: 8, name: "CET_LOCATION"},
    {no: 9, name: "CET_PERSON"},
    {no: 10, name: "CET_PHONE_NUMBER"},
    {no: 11, name: "CET_MEDICAL_LICENSE"},
    {no: 12, name: "CET_URL"},
    {no: 13, name: "CET_US_BANK_NUMBER"},
    {no: 14, name: "CET_US_DRIVER_LICENSE"},
    {no: 15, name: "CET_US_ITIN"},
    {no: 16, name: "CET_US_PASSPORT"},
    {no: 17, name: "CET_US_SSN"},
    {no: 18, name: "CET_POSTAL_CODE"},
  ],
);

