// @generated by protoc-gen-es v1.7.2 with parameter "target=js+dts"
// @generated from file api/v1alpha1/org/idp/entities.proto (package api.v1alpha1.org.idp, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { IdpClient } from "../../../commons/org/idp_pb.js";

/**
 * CreateClientReq is a request to make a client.
 *
 * @generated from message api.v1alpha1.org.idp.CreateClientReq
 */
export const CreateClientReq = proto3.makeMessageType(
  "api.v1alpha1.org.idp.CreateClientReq",
  () => [
    { no: 1, name: "client", kind: "message", T: IdpClient },
  ],
);

/**
 * CreateClientResp returns the response from creating a client.
 *
 * @generated from message api.v1alpha1.org.idp.CreateClientResp
 */
export const CreateClientResp = proto3.makeMessageType(
  "api.v1alpha1.org.idp.CreateClientResp",
  () => [
    { no: 1, name: "already_exists", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "client", kind: "message", T: IdpClient },
  ],
);

/**
 * DeleteClientReq is a request to delete a client.
 *
 * @generated from message api.v1alpha1.org.idp.DeleteClientReq
 */
export const DeleteClientReq = proto3.makeMessageType(
  "api.v1alpha1.org.idp.DeleteClientReq",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * DeleteClientResp determines if the client is deleted successfully.
 *
 * @generated from message api.v1alpha1.org.idp.DeleteClientResp
 */
export const DeleteClientResp = proto3.makeMessageType(
  "api.v1alpha1.org.idp.DeleteClientResp",
  () => [
    { no: 1, name: "not_found", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ],
);

/**
 * UpdateClientReq is a request to update an existing client.
 *
 * @generated from message api.v1alpha1.org.idp.UpdateClientReq
 */
export const UpdateClientReq = proto3.makeMessageType(
  "api.v1alpha1.org.idp.UpdateClientReq",
  () => [
    { no: 1, name: "client", kind: "message", T: IdpClient },
  ],
);

/**
 * UpdateClientResp returns the response from updating a client.
 *
 * @generated from message api.v1alpha1.org.idp.UpdateClientResp
 */
export const UpdateClientResp = proto3.makeMessageType(
  "api.v1alpha1.org.idp.UpdateClientResp",
  () => [
    { no: 1, name: "not_found", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ],
);

/**
 * @generated from message api.v1alpha1.org.idp.ListClientsReq
 */
export const ListClientsReq = proto3.makeMessageType(
  "api.v1alpha1.org.idp.ListClientsReq",
  [],
);

/**
 * @generated from message api.v1alpha1.org.idp.ListClientsResp
 */
export const ListClientsResp = proto3.makeMessageType(
  "api.v1alpha1.org.idp.ListClientsResp",
  () => [
    { no: 1, name: "clients", kind: "message", T: IdpClient, repeated: true },
  ],
);

