// @generated by protoc-gen-es v1.2.0 with parameter "target=js+dts"
// @generated from file annotations/perms/license.proto (package annotations.perms, syntax proto3)
/* eslint-disable */
// @ts-nocheck

/**
 * Application contains license/permission application name constants.
 *
 * @generated from enum annotations.perms.Application
 */
export declare enum Application {
  /**
   * @generated from enum value: APPLICATION_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: APPLICATION_AGENT = 1;
   */
  AGENT = 1,

  /**
   * @generated from enum value: APPLICATION_BUSINESS_INTELLIGENCE = 2;
   */
  BUSINESS_INTELLIGENCE = 2,

  /**
   * @generated from enum value: APPLICATION_DELIVERY_SERVICE = 3;
   */
  DELIVERY_SERVICE = 3,

  /**
   * @generated from enum value: APPLICATION_DEV_TOOLS = 4;
   */
  DEV_TOOLS = 4,

  /**
   * @generated from enum value: APPLICATION_INTEGRATIONS = 5;
   */
  INTEGRATIONS = 5,

  /**
   * @generated from enum value: APPLICATION_LIST_MANAGEMENT_SERVICES = 6;
   */
  LIST_MANAGEMENT_SERVICES = 6,

  /**
   * @generated from enum value: APPLICATION_NATURAL_LANGUAGE_COMPLIANCE = 7;
   */
  NATURAL_LANGUAGE_COMPLIANCE = 7,

  /**
   * @generated from enum value: APPLICATION_OMNI_BOSS = 8;
   */
  OMNI_BOSS = 8,

  /**
   * @generated from enum value: APPLICATION_ORGANIZATION = 9;
   */
  ORGANIZATION = 9,

  /**
   * @generated from enum value: APPLICATION_ROOM_303 = 10;
   */
  ROOM_303 = 10,

  /**
   * @generated from enum value: APPLICATION_SCORECARDS = 11;
   */
  SCORECARDS = 11,

  /**
   * @generated from enum value: APPLICATION_SCRIPTS = 12;
   */
  SCRIPTS = 12,

  /**
   * @generated from enum value: APPLICATION_TICKETS = 13;
   */
  TICKETS = 13,

  /**
   * @generated from enum value: APPLICATION_VOICE_ANALYTICS = 14;
   */
  VOICE_ANALYTICS = 14,

  /**
   * @generated from enum value: APPLICATION_WORK_FORCE_MANAGEMENT = 15;
   */
  WORK_FORCE_MANAGEMENT = 15,
}

/**
 * Card contains license/permission card label constants.
 *
 * @generated from enum annotations.perms.Card
 */
export declare enum Card {
  /**
   * @generated from enum value: CARD_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Organization cards.
   *
   * @generated from enum value: CARD_ORGANIZATION = 1;
   */
  ORGANIZATION = 1,

  /**
   * @generated from enum value: CARD_USERS = 2;
   */
  USERS = 2,

  /**
   * @generated from enum value: CARD_AGENTS = 3;
   */
  AGENTS = 3,

  /**
   * @generated from enum value: CARD_PERMISSION_GROUPS = 4;
   */
  PERMISSION_GROUPS = 4,

  /**
   * @generated from enum value: CARD_LABELS = 5;
   */
  LABELS = 5,

  /**
   * @generated from enum value: CARD_TRUSTS = 6;
   */
  TRUSTS = 6,

  /**
   * @generated from enum value: CARD_HUNT_GROUPS = 7;
   */
  HUNT_GROUPS = 7,

  /**
   * @generated from enum value: CARD_SOUNDBOARD = 8;
   */
  SOUNDBOARD = 8,

  /**
   * @generated from enum value: CARD_SUBSCRIPTIONS = 9;
   */
  SUBSCRIPTIONS = 9,
}

