// @generated by protoc-gen-connect-es v0.13.0
// @generated from file api/v1alpha1/billing/service.proto (package api.v1alpha1.billing, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ExportGeneratedInvoiceReq, ExportGeneratedInvoiceRes, GetBillingPlanReq, GetBillingPlanRes, GetInvoiceReq, GetInvoiceRes, UpdateBillingPlanReq, UpdateBillingPlanRes } from "./entities_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service api.v1alpha1.billing.Billing
 * @deprecated
 */
export declare const Billing: {
  readonly typeName: "api.v1alpha1.billing.Billing",
  readonly methods: {
    /**
     * @generated from rpc api.v1alpha1.billing.Billing.GetBillingPlan
     * @deprecated
     */
    readonly getBillingPlan: {
      readonly name: "GetBillingPlan",
      readonly I: typeof GetBillingPlanReq,
      readonly O: typeof GetBillingPlanRes,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc api.v1alpha1.billing.Billing.UpdateBillingPlan
     * @deprecated
     */
    readonly updateBillingPlan: {
      readonly name: "UpdateBillingPlan",
      readonly I: typeof UpdateBillingPlanReq,
      readonly O: typeof UpdateBillingPlanRes,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc api.v1alpha1.billing.Billing.GetInvoice
     * @deprecated
     */
    readonly getInvoice: {
      readonly name: "GetInvoice",
      readonly I: typeof GetInvoiceReq,
      readonly O: typeof GetInvoiceRes,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc api.v1alpha1.billing.Billing.ExportGeneratedInvoice
     * @deprecated
     */
    readonly exportGeneratedInvoice: {
      readonly name: "ExportGeneratedInvoice",
      readonly I: typeof ExportGeneratedInvoiceReq,
      readonly O: typeof ExportGeneratedInvoiceRes,
      readonly kind: MethodKind.Unary,
    },
  }
};

