// @generated by protoc-gen-connect-es v0.9.1
// @generated from file api/v1alpha1/agentsmith/service.proto (package api.v1alpha1.agentsmith, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { FollowAgentReq, FollowAgentRes } from "./service_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * AgentSmith is the Public API for the AgentSmith service. This service provides the methods for public integrations
 * to follow agents and/or create virtual agents.
 *
 * @generated from service api.v1alpha1.agentsmith.AgentSmith
 */
export declare const AgentSmith: {
  readonly typeName: "api.v1alpha1.agentsmith.AgentSmith",
  readonly methods: {
    /**
     * FollowAgent method find an agent identified by user_id or asm_session_id and return a stream of events
     * associated with the current session of the user and long as the session lives regardless if the agent is
     * using the omni interface or neo interface.
     * When the agent is in a voice session one of the first messages received will be AgentVoiceStartEvent that
     * contains a sip dial url that can be used to connect to the agent's voice session.
     *
     * @generated from rpc api.v1alpha1.agentsmith.AgentSmith.FollowAgent
     */
    readonly followAgent: {
      readonly name: "FollowAgent",
      readonly I: typeof FollowAgentReq,
      readonly O: typeof FollowAgentRes,
      readonly kind: MethodKind.ServerStreaming,
    },
  }
};

