// Copyright (c) 2020, TCN Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @generated by protoc-gen-connect-es v0.13.0
// @generated from file api/v1alpha1/workflows/service.proto (package api.v1alpha1.workflows, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateWorkflowDefinitionRequest, CreateWorkflowDefinitionResponse, GetWorkflowDefinitionRequest, GetWorkflowDefinitionResponse, ListWorkflowDefinitionsRequest, ListWorkflowDefinitionsResponse, UpdateWorkflowDefinitionRequest, UpdateWorkflowDefinitionResponse, ValidateWorkflowDefinitionRequest, ValidateWorkflowDefinitionResponse } from "./service_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * WorkflowDefinitionPersistService is the service that provides CRUD operations for FlowDefinitions.
 * PERMISSION_WORKFLOWS is required for all operations
 *
 * @generated from service api.v1alpha1.workflows.WorkflowDefinitionPersistService
 */
export const WorkflowDefinitionPersistService = {
  typeName: "api.v1alpha1.workflows.WorkflowDefinitionPersistService",
  methods: {
    /**
     * CreateFlowDefinition creates a new flow definition in the database
     *
     * @generated from rpc api.v1alpha1.workflows.WorkflowDefinitionPersistService.CreateWorkflowDefinition
     */
    createWorkflowDefinition: {
      name: "CreateWorkflowDefinition",
      I: CreateWorkflowDefinitionRequest,
      O: CreateWorkflowDefinitionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetWorkflowDefinition retrieves a flow definition from the database
     *
     * @generated from rpc api.v1alpha1.workflows.WorkflowDefinitionPersistService.GetWorkflowDefinition
     */
    getWorkflowDefinition: {
      name: "GetWorkflowDefinition",
      I: GetWorkflowDefinitionRequest,
      O: GetWorkflowDefinitionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * ListWorkflowDefinitions retrieves a list of flow definitions from the database optionally filtered by the owning application
     * if application is not specified, all flow definitions for the org are returned
     *
     * @generated from rpc api.v1alpha1.workflows.WorkflowDefinitionPersistService.ListWorkflowDefinitions
     */
    listWorkflowDefinitions: {
      name: "ListWorkflowDefinitions",
      I: ListWorkflowDefinitionsRequest,
      O: ListWorkflowDefinitionsResponse,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * UpdateWorkflowDefinition updates a flow definition in the database. Only the name, description and definition graph itself are updated
     *
     * @generated from rpc api.v1alpha1.workflows.WorkflowDefinitionPersistService.UpdateWorkflowDefinition
     */
    updateWorkflowDefinition: {
      name: "UpdateWorkflowDefinition",
      I: UpdateWorkflowDefinitionRequest,
      O: UpdateWorkflowDefinitionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * ValidateWorkflowDefinition validates a flow definition in the database. Only the name, description and definition graph itself are updated
     *
     * @generated from rpc api.v1alpha1.workflows.WorkflowDefinitionPersistService.ValidateWorkflowDefinition
     */
    validateWorkflowDefinition: {
      name: "ValidateWorkflowDefinition",
      I: ValidateWorkflowDefinitionRequest,
      O: ValidateWorkflowDefinitionResponse,
      kind: MethodKind.Unary,
    },
  }
};

