// Copyright (c) 2020, TCN Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @generated by protoc-gen-connect-es v0.13.0
// @generated from file api/v1alpha1/workflows/service.proto (package api.v1alpha1.workflows, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateFlowDefinitionRequest, CreateFlowDefinitionResponse, GetFlowDefinitionRequest, GetFlowDefinitionResponse, ListFlowDefinitionsRequest, ListFlowDefinitionsResponse, UpdateFlowDefinitionRequest, UpdateFlowDefinitionResponse, ValidateFlowDefinitionRequest, ValidateFlowDefinitionResponse } from "./service_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * FlowDefinitionPersistService is the service that provides CRUD operations for FlowDefinitions.
 * PERMISSION_WORKFLOWS is required for all operations
 *
 * @generated from service api.v1alpha1.workflows.FlowDefinitionPersistService
 */
export declare const FlowDefinitionPersistService: {
  readonly typeName: "api.v1alpha1.workflows.FlowDefinitionPersistService",
  readonly methods: {
    /**
     * CreateFlowDefinition creates a new flow definition in the database
     *
     * @generated from rpc api.v1alpha1.workflows.FlowDefinitionPersistService.CreateFlowDefinition
     */
    readonly createFlowDefinition: {
      readonly name: "CreateFlowDefinition",
      readonly I: typeof CreateFlowDefinitionRequest,
      readonly O: typeof CreateFlowDefinitionResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * GetFlowDefinition retrieves a flow definition from the database
     *
     * @generated from rpc api.v1alpha1.workflows.FlowDefinitionPersistService.GetFlowDefinition
     */
    readonly getFlowDefinition: {
      readonly name: "GetFlowDefinition",
      readonly I: typeof GetFlowDefinitionRequest,
      readonly O: typeof GetFlowDefinitionResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * ListFlowDefinitions retrieves a list of flow definitions from the database optionally filtered by the owning application
     * if application is not specified, all flow definitions for the org are returned
     *
     * @generated from rpc api.v1alpha1.workflows.FlowDefinitionPersistService.ListFlowDefinitions
     */
    readonly listFlowDefinitions: {
      readonly name: "ListFlowDefinitions",
      readonly I: typeof ListFlowDefinitionsRequest,
      readonly O: typeof ListFlowDefinitionsResponse,
      readonly kind: MethodKind.ServerStreaming,
    },
    /**
     * UpdateFlowDefinition updates a flow definition in the database. Only the name, description and definition graph itself are updated
     *
     * @generated from rpc api.v1alpha1.workflows.FlowDefinitionPersistService.UpdateFlowDefinition
     */
    readonly updateFlowDefinition: {
      readonly name: "UpdateFlowDefinition",
      readonly I: typeof UpdateFlowDefinitionRequest,
      readonly O: typeof UpdateFlowDefinitionResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * ValidateFlowDefinition validates a flow definition in the database. Only the name, description and definition graph itself are updated
     *
     * @generated from rpc api.v1alpha1.workflows.FlowDefinitionPersistService.ValidateFlowDefinition
     */
    readonly validateFlowDefinition: {
      readonly name: "ValidateFlowDefinition",
      readonly I: typeof ValidateFlowDefinitionRequest,
      readonly O: typeof ValidateFlowDefinitionResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

