// @generated by protoc-gen-connect-es v0.10.1
// @generated from file api/v1alpha1/workflows/service.proto (package api.v1alpha1.workflows, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { DeleteFlowDefinitionRequest, DeleteFlowDefinitionResponse, GetFlowDefinitionRequest, GetFlowDefinitionResponse, ListFlowDefinitionsRequest, ListFlowDefinitionsResponse, SaveFlowDefinitionRequest, SaveFlowDefinitionResponse } from "./entities_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service api.v1alpha1.workflows.WorkflowsDefinitionsService
 */
export const WorkflowsDefinitionsService = {
  typeName: "api.v1alpha1.workflows.WorkflowsDefinitionsService",
  methods: {
    /**
     * ListFlowDefinitions lists flow definitions
     *
     * @generated from rpc api.v1alpha1.workflows.WorkflowsDefinitionsService.ListFlowDefinitions
     */
    listFlowDefinitions: {
      name: "ListFlowDefinitions",
      I: ListFlowDefinitionsRequest,
      O: ListFlowDefinitionsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * SaveFlowDefinition creates or updates a flow definition
     *
     * @generated from rpc api.v1alpha1.workflows.WorkflowsDefinitionsService.SaveFlowDefinition
     */
    saveFlowDefinition: {
      name: "SaveFlowDefinition",
      I: SaveFlowDefinitionRequest,
      O: SaveFlowDefinitionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetFlowDefinition gets a flow definition
     *
     * @generated from rpc api.v1alpha1.workflows.WorkflowsDefinitionsService.GetFlowDefinition
     */
    getFlowDefinition: {
      name: "GetFlowDefinition",
      I: GetFlowDefinitionRequest,
      O: GetFlowDefinitionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * DeleteFlowDefinition deletes a flow definition
     *
     * @generated from rpc api.v1alpha1.workflows.WorkflowsDefinitionsService.DeleteFlowDefinition
     */
    deleteFlowDefinition: {
      name: "DeleteFlowDefinition",
      I: DeleteFlowDefinitionRequest,
      O: DeleteFlowDefinitionResponse,
      kind: MethodKind.Unary,
    },
  }
};

